package Errors;

public enum Errors {
    /** USERNAME ERRORS*/
    USERNAME_MISSING,
    USERNAME_INVALID,
    USERNAME_WRONG_LENGTH,
    USERNAME_ALREADY_EXISTS,
    ACCOUNT_NAME_MISSING,
    ACCOUNT_NAME_WRONG_LENGTH,
    ACCOUNT_DOESNT_EXIST,

    /** EMAIL ERRORS*/
    EMAIL_MISSING,
    EMAIL_INVALID,
    EMAIL_ALREADY_EXISTS,

    /**ADDRESS ERRORS*/
    ADDRESS_INVALID,
    ADDRESS_WRONG_LENGTH,

    /**TELEPHONE ERRORS*/
    TELEPHONE_NUMBER_MISSING,
    TELEPHONE_NUMBER_INVALID,

    /**COMPANY ERRORS*/
    COMPANY_NAME_MISSING,
    COMPANY_NAME_WRONG_LENGTH,
    COMPANY_NAME_INVALID,

    /** PASSWORD ERRORS */
    OLD_PASSWORD_MISSING,
    PASSWORD_MISSING,
    PASSWORD_WRONG_LENGTH,
    PASSWORD_REQUIRES_UPPERCASE,
    PASSWORD_REQUIRES_LOWERCASE,
    PASSWWORD_REQUIRES_NUMERIC,
    PASSWORD_REQUIRES_NONALPHANUMERIC,

    /** PRODUCT ERRORS*/
    PRODUCT_NAME_MISSING,
    PRODUCT_DOESNT_EXIST,
    PRODUCT_NAME_INVALID,

    /** ORDERS ERRORS*/
    STATUS_MISSING,
    STATUS_INVALID,
    DESIRED_PROPERTY_WRONG_LENGTH,

}
